export const GET_INSTRUCTORS = 'GET_INSTRUCTORS';
export const DELETE_INSTRUCTOR = 'DELETE_INSTRUCTOR';
export const ADD_INSTRUCTOR = 'ADD_INSTRUCTOR';
export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const GET_MESSAGES = 'GET_MESSAGES';

